apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: ll-ambulance-ufe
spec:   
  module-uri: http://ll-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: ll-ambulance-wl-app
      path: ll-ambulance-wl            
      title: Zoznam čakajúcich LL
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii     
      attributes:                   
        - name: base-path
          value: /ui/ll-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false                    
  proxy: true                                           
  hash-suffix: v1alpha2                        
