apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: bado-ambulance-ufe
spec:   
  module-uri: http://bado-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: bado-ambulance-wl-app
      path: bado-ambulance-wl            
      title: Zoznam čakajúcich bado
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii     
      attributes:                   
        - name: base-path
          value: /ui/bado-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false                    
  proxy: true                                           
  hash-suffix: v1alpha2                        
