apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata: 
  name: bamat-ambulance-ufe
spec:   
  module-uri: http://bamat-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: bamat-ambulance-wl-list
      path: bamat-ambulance-wl            
      title: Zoznam čakajúcich Bamat
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii     
      attributes:                   
        - name: base-path
          value: /ui/bamat-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false                    
  proxy: true                                           
  hash-suffix: v1alpha2                        
