apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: af-ambulance-ufe
spec:
  module-uri: http://af-ambulance-ufe.wac-hospital/build/ambulance-list.esm.js
  navigation:
    - element: af-ambulance-wl-app
      path: af-ambulance-wl
      title: Zoznam čakajúcich AF
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
      attributes:
        - name: base-path
          value: /ui/af-ambulance-wl/
        - name: ambulance
          value: bobulova
  preload: false
  proxy: true
  hash-suffix: v1alpha2
